export const PAGE_HOME = "HOME";
export const PAGE_USER_PROFILE = "USERPROFILE";
export const PAGE_USER_ADMIN = "ADMINPROFILE";
export const PAGE_CALENDAR = "CALENDAR";
export const PAGE_MYLESSONS = "MYLESSONS";

export const PAGE_ADMIN_COURSES = "ADMINCOURSES";
export const PAGE_ADMIN_PROFESSORS = "ADMINPROFESSORS";
export const PAGE_ADMIN_TEACHINGS = "ADMINTEACHINGS";
export const PAGE_ADMIN_BOOKINGS = "ADMINBOOKINGS";

export const REPETITION_STATUS_DELETED = "deleted";
export const REPETITION_STATUS_DONE = "done";